version: '3'

services:
    graphql.app:
        build:
            context: ./graphql.app/
            dockerfile: Dockerfile
        expose:
            - 3000
        ports:
            - 3000:3000
        restart: on-failure
        volumes:
            - ./graphql.app/:/app

    # here could be the other applications
